on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: charts/ misc/ loadbalancer/ storage/
          config_data: |
            extends: default
            rules:
              line-length:
                max: 120
